assemblyai:
  api:
    key: ${ASSEMBLYAI_API_KEY}
    url: https://api.assemblyai.com/v2

spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: assemblyai-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  minio:
    url: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: audio-bucket