FROM maven:3.9-amazoncorretto-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM amazoncorretto:21-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
COPY src/main/resources/ /app/resources/
RUN mkdir -p /app/logs && chmod 777 /app/logs
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]