server:
  port: 8080
  address: 0.0.0.0

management:
  server:
    port: 8081
    address: 0.0.0.0
  endpoints:
    web:
      base-path: /actuator

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8080/.well-known/jwks.json
  h2:
    console:
      enabled: false
  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    ru.polyrythms: INFO
  file:
    name: /app/logs/weather-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30