spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: audio-service-group-test
      auto-offset-reset: earliest

minio:
  url: http://minio:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket: audio-bucket-test

assemblyai:
  api:
    key: ${ASSEMBLYAI_API_KEY}

logging:
  level:
    root: INFO
    org.springframework.kafka: WARN