spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: audio-service-group-prod
      auto-offset-reset: latest
      max-poll-records: 10

minio:
  url: http://minio:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket: audio-bucket-prod

assemblyai:
  api:
    key: ${ASSEMBLYAI_API_KEY}

logging:
  level:
    root: WARN
    ru.polyrythms: INFO
  file:
    name: /app/logs/audio-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30