spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: telegram-bot-group-prod
      auto-offset-reset: latest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

minio:
  url: http://minio:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket: audio-bucket-prod

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

logging:
  level:
    root: WARN
    ru.polyrythms: INFO
  file:
    name: /app/logs/telegram-bot.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30