spring:
  application:
    name: telegram-bot
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: prod

telegram:
  thread-pool:
    inbound:
      core-size: 0  # 0 = auto = количество ядер
      queue-capacity: 1
    outbound:
      core-size: 0  # 0 = auto = количество ядер
      queue-capacity: 1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

app:
  kafka:
    topics:
      audio-processing: ${AUDIO_PROCESSING_TOPIC:audio-processing-topic}
      audio-result: ${AUDIO_RESULT_TOPIC:audio-result-topic}
    partitions: 6
    replicas: 1

logging:
  level:
    root: INFO
    ru.polyrythms: DEBUG